package entity;
// Generated 2012-03-06 12:48:16 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article  implements java.io.Serializable {


     private Integer articleId;
     private User user;
     private Date date;
     private String name;
     private String article;
     private boolean delete;
     private boolean marked;
     private Set<Comment> comments = new HashSet<Comment>(0);

    public Article() {
    }

	
    public Article(User user, Date date, String name, String article) {
        this.user = user;
        this.date = date;
        this.name = name;
        this.article = article;
    }
    public Article(User user, Date date, String name, String article, Set<Comment> comments) {
       this.user = user;
       this.date = date;
       this.name = name;
       this.article = article;
       this.comments = comments;
    }
   
    public Integer getArticleId() {
        return this.articleId;
    }
    
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }
    public boolean isDelete() {
        return delete;
    }

    public void setDelete(boolean delete) {
        this.delete = delete;
    }

    public boolean isMarked() {
        return marked;
    }

    public void setMarked(boolean marked) {
        this.marked = marked;
    }
    

}


