package entity;
// Generated 2012-03-06 12:48:16 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String login;
     private String password;
     private String mail;
     private Date date;
     private Character sex;
     private int rule;
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<Comment> comments = new HashSet<Comment>(0);

    public User() {
    }

	
    public User(String login, String password, String mail, int rule) {
        this.login = login;
        this.password = password;
        this.mail = mail;
        this.rule = rule;
    }
    public User(String login, String password, String mail, int rule,Date date,Character sex) {
        this.login = login;
        this.password = password;
        this.mail = mail;
        this.rule = rule;
        this.sex=sex;
        this.date=date;
    }
    public User(String login, String password, String mail, Date date, Character sex, int rule, Set<Article> articles, Set<Comment> comments) {
       this.login = login;
       this.password = password;
       this.mail = mail;
       this.date = date;
       this.sex = sex;
       this.rule = rule;
       this.articles = articles;
       this.comments = comments;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Character getSex() {
        return this.sex;
    }
    
    public void setSex(Character sex) {
        this.sex = sex;
    }
    public int getRule() {
        return this.rule;
    }
    
    public void setRule(int rule) {
        this.rule = rule;
    }
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    public Set<Comment> getComments() {
        return this.comments;
    }
    
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }




}


